<a href="https://colab.research.google.com/github/dinooooooi/dinooooi/blob/main/0405%EA%B8%88%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

466~486
#Chaper 8. 텍스트 분석

##01. 텍스트 분석 이해
비정형 데이터 텍스트 분석

어떻게 피처 형태로 추출하고 추출된 피처에 의미 있는 값을 부여하는지가 중요
= 피처 벡터화, 피처 추출

###텍스트 분석 수행 프로세스
1. 텍스트 사전준비작업
2. 피처 벡터화/추출
3. ML 모델 수립 및 학습/예측/평가

###파이썬 기반의 NLP, 텍스트 분석 패키지
* NLTK : 대표적인 NLP 패키지
* Gensim
* SpaCy

##02. 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화
### 클렌징
텍스트에서 분석에 오히려 방해가 되는 불필요한 문자, 기호 등을 사전에 제거하는 작업
###텍스트 토큰화
문장 토큰화: 문서에서 문장을 분리

마침표, 개행문자 등 문장의 마지막을 뜻하는 기호에 따라 분리하는 것이 일반적


In [1]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


3개의 문장으로 된 문자열을 가지고 있음

단어 토큰화: 문장에서 단어를 분리

공백, 콤마, 마침표, 개행문자 드응로 단어를 분리하지만 정규 표현식을 이용해 다양한 유형으로 토큰화 수행 가능

단어의 순서가 중요하지 않은 경우 단어 토큰화만 사용해도 충분

In [2]:
from nltk import word_tokenize
sentence = "The Matrix is everywhere its all around us, hear even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'hear', 'even', 'in', 'this', 'room', '.']


sent_tokenize와 word_tokenize  조합

In [3]:
from nltk import word_tokenize, sent_tokenize

#여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):

  # 문장별로 분리 토큰
  sentences = sent_tokenize(text)
  # 분리된 문장별 단어 토큰화
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens

# 여러 문장에 대해 문장별 단어 토큰화 수행.
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


###스톱 워드 제거

스톱워드: 분석에 큰 의미가 없는 단어

언어별로 목록화되어 있음

In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
print('영어 stop words 개수:', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


word_tokens리스트에 대해서 stopwords를 필터링으로 제거

In [7]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens=[]
# 위 예제에서 3개의 문장별로 얻은 word_tokens list에 대해 스톱 워드를 제거하는 반복문
for sentence in word_tokens:
  filtered_words=[]
  #개별 문장별로 토큰화된 문장 list에 대해 스톱 워드를 제거하는 반복문
  for word in sentence:
    # 소문자로 모두 변환합니다.
    word = word.lower()
    #토큰화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


### stemming과 Lemmatization

문법적인 요소를 제외한 원형 단어를 찾음

Lemmatization이 더 정교 - 의미론적인 기반에서 단어의 원형 찾음

Stemming은 일반적인 방법

In [8]:
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [9]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses','v'), lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'), lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'), lemma.lemmatize('fanciest','a'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


amuse amuse amuse
happy happy
fancy fancy


더 정확하게 원형 단어 추출

##03. Bag of Words - BOW
단어를 문맥이나 순서를 무시하고 일관적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델
###BOW 피처 벡터화
텍스트는 특정 의미를 가지는 숫자형 값인 벡터값으로 변환 : 피처 벡터화

* 카운트 기반의 벡터화

단어 피처에 값을 부여할 때 각 문서에서 해당 단어가 나타나는 횟수

언어의 특성상 문장에서 자주 사용될 수 밖에 없는 단어까지 높은 값을 부

* TF-IDF 기반의 벡터화

개별 문서에서 자주 나타나는 단어에 높은 가중치를 주되, 모든 문서에서 자주 나타나는 단어에 대해서는 패널티를 주는 방식으로 값을 부여
###사이킷런의 count 및 TF-IDF 벡터화 구현: CountVectorizer, TfidfVectorizer
 CountVectorizer 클래스 : 피처 벡터화, 소문자 일괄 변환, 토큰화, 스톱 워드 필터링 등 텍스트 전처리

 영어의 경우 모든 문자를 소문자로 변경하는 등의 전처리

 디폴트로 단어 기준으로 n_gram_range를 반영해 각 단어 토큰화

 텍스트 정규화 stop_words 파라미터가 주어진 경우 스톱워드 필터링만 가능

 TfidfVectorizer 클래스 : 비슷

###BOW 벡터화를 위한 희소 행렬
대규모 행렬의 대부분의 값을 0이 차지하는 행렬을 가리켜 희소 행렬

BOW 형태를 가진 언어 모델의 피처 벡터화는 대부분 희소 행렬

물리적으로 적은 메모리 공간을 차지할 수 있도록 변환 : COO형식과 CSR 형식

###희소 행렬- COO 형식

0이 아닌 데이터만 별도의 데이터 배열에 저장하고 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장하는 방식

사이파이 이용

In [10]:
import numpy as np
dense = np.array([[3,0,1],[0,2,0]])

In [11]:
from scipy import sparse

# 0이 아닌 데이터 추출
data = np.array([3,1,2])

# 0이 아닌 데이터의 행 위치와 열 위치를 각각 배열로 생성
row_pos = np.array([0,0,1])      # 3:(0,0)/1:(0,2)/2:(1,1)
col_pos = np.array([0,2,1])

#saprse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

밀집 형태의 행렬로 출력

In [12]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

###희소 행렬 - CSR 형식

COO 형식의 문제점 : 순차적인 같은 값이 반복적으로 나타남

행 위치 배열의 고유한 값의 시작 위치만 표기하는 방법으로 반복 제거

사이파이의 csr_matrix 클래스를 이용

0이 아닌 데이터 배열과 열 위치 배열, 행 위치 배열의 고유값의 시작 위치 배열을 csr_matrix의 생성 파라미터로 입력

In [13]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

# 0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

# 행 위치와 열 위치를 각각 array로 생성
row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0,2,7,9,10,12,13])

# CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [14]:
dense3 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)

In [15]:
print(coo.toarray())
print(csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
